export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Argentina", "Armenia", "Australia",
  "Austria", "Azerbaijan", "Bangladesh", "Belarus", "Belgium", "Bolivia",
  "Bosnia and Herzegovina", "Brazil", "Bulgaria", "Cambodia", "Cameroon",
  "Canada", "Chile", "China", "Colombia", "Croatia", "Cuba", "Czech Republic",
  "Denmark", "Dominican Republic", "Ecuador", "Egypt", "Estonia", "Ethiopia",
  "Finland", "France", "Georgia", "Germany", "Ghana", "Greece", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
  "Italy", "Ivory Coast", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kosovo",
  "Kurdistan", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Libya",
  "Lithuania", "Malaysia", "Mexico", "Mongolia", "Morocco", "Myanmar",
  "Nepal", "Netherlands", "New Zealand", "Nigeria", "North Macedonia",
  "Norway", "Pakistan", "Palestine", "Peru", "Philippines", "Poland",
  "Portugal", "Romania", "Russia", "Saudi Arabia", "Senegal", "Serbia",
  "Singapore", "Slovakia", "Slovenia", "Somalia", "South Africa",
  "South Korea", "Spain", "Sri Lanka", "Sudan", "Sweden", "Switzerland",
  "Syria", "Taiwan", "Tajikistan", "Thailand", "Tunisia", "Turkey",
  "Turkmenistan", "Uganda", "Ukraine", "United Kingdom", "United States",
  "Uzbekistan", "Venezuela", "Vietnam", "Yemen", "Fusion / Mixed", "Other",
] as const;
