export const UNIT_LABELS: Record<"en" | "fi", Record<string, string>> = {
  en: {
    g: "g",
    kg: "kg",
    ml: "ml",
    dl: "dl",
    l: "l",
    tsp: "tsp",
    tbsp: "tbsp",
    cup: "cup",
    oz: "oz",
    lb: "lb",
    pcs: "pcs",
    clove: "clove",
    pinch: "pinch",
    can: "can",
    package: "package",
  },
  fi: {
    g: "g",
    kg: "kg",
    ml: "ml",
    dl: "dl",
    l: "l",
    tsp: "tl",
    tbsp: "rkl",
    cup: "kupillinen",
    oz: "unssi",
    lb: "naula",
    pcs: "kpl",
    clove: "kynsi",
    pinch: "ripaus",
    can: "tölkki",
    package: "pakkaus",
  },
};
